apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secure-ai-backend-pvc
  namespace: secure-ai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
