apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secure-ai-backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
