apiVersion: v1
kind: Secret
metadata:
  name: secure-ai-backend-secret
  namespace: secure-ai
type: Opaque
stringData:
  ADMIN_PASSWORD_HASH: "replace-me"
  USER_PASSWORD_HASH: "replace-me"
  JWT_SECRET: "replace-with-a-random-string-of-at-least-32-characters"
